DChat/DChat.Web/Controllers/HomeController.cs
using DChat.DataAccess;
using DChat.Model.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DChat.Core.interfaces;

namespace DChat.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IMemberService _member_service;
        //
        // GET: /Home/
        public HomeController(IMemberService ser)
        {
            _member_service = ser;
        }

        public ActionResult Index()
        {
            if (HttpContext.Request.Cookies.Get("DAKER_USR_ID") == null)
            {
                return RedirectToAction("Login", "Member");
            }
            //创建上下文
            //ChatDbContext db = new ChatDbContext();
            ////创建数据库
            ////db.Database.CreateIfNotExists();
            //IEnumerable<MsgItem> list = db.MsgItems.ToList();


            ////创建表 且将字段加入
            //UserInfo userInfo = new UserInfo();
            //userInfo.Name = "windfierce";
            ////将表加入数据库
            //db.UserInfos.Add(userInfo);
            //MsgItem msg = new MsgItem
            //{
            //    Id = Guid.NewGuid(),
            //    MsgContent = "aaa",
            //    SendTime = DateTime.Now,
            //    UserId = 1
            //};
            //msg.Pre = msg;

            //db.MsgItems.Add(msg);
            //db.SaveChanges();
            //MsgItem msg2 = new MsgItem
            //{
            //    Id = Guid.NewGuid(),
            //    MsgContent = "aaa",
            //    SendTime = DateTime.Now,
            //    UserId = 1,
            //    Pre = msg
            //};
            //db.MsgItems.Add(msg2);
            //db.SaveChanges();

            int usrid = int.Parse(HttpContext.Request.Cookies.Get("DAKER_USR_ID").Value);
            var member = _member_service.GetByID(usrid);
            return View(member);
        }
    }
}

DChat/DChat.Web/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DChat.Core.context;
using DChat.Core.interfaces;
using DChat.Model.Models;

namespace DChat.Web.Controllers
{
    public class MemberController : Controller
    {
        private readonly IMemberService _service;
        //
        // GET: /Member/
        public MemberController(IMemberService service)
        {
            _service = service;
        }

        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Login()
        {
            return View();

        }

        [HttpPost]
        public JsonResult Login(string name, string password)
        {
            var member = _service.Login(name, password);
            if (member != null)
            {
                HttpCookie cookie = new HttpCookie("DAKER_USR_ID", member.Id.ToString());
                cookie.Expires = DateTime.Now.AddMinutes(30);
                Response.Cookies.Add(cookie);
                UsersContext.AddOnLine(member);
                return Json(new { status = 1, Data = member }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { status = 0, message = "用户名或者密码错误" });

            }
        }

        public JsonResult ComeChat(int id)
        {
            var member = _service.GetByID(id);
            UsersContext.AddOnLine(member);
            return Json(new {status = 1},JsonRequestBehavior.AllowGet);
        }

        public JsonResult Info()
        {
            if (Request.Cookies.Get("DAKER_USR_ID") != null)
            {
                int id = int.Parse(Request.Cookies.Get("DAKER_USR_ID").Value);
                var member = _service.GetByID(id);
                return Json(new { status = 1, Data = member }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { status = 0},JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Regester()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Regester(UserInfo usr)
        {
            try
            {
                if (!string.IsNullOrEmpty(usr.Name) && !string.IsNullOrEmpty(usr.Password))
                {
                    var ur = _service.Regester(usr);
                    _service.Login(ur.Name, ur.Password);
                    HttpCookie cookie = new HttpCookie("DAKER_USR_ID", ur.Id.ToString());
                    cookie.Expires = DateTime.Now.AddMinutes(30);
                    Response.Cookies.Add(cookie);
                    Response.Redirect("../Home/index");
                }
                return Content("用户名和密码不能为空.");

            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }

        }

        public JsonResult Onlines()
        {
            return Json(new { status = 1, Data = UsersContext.Users }, JsonRequestBehavior.AllowGet);

        }

        public void OffLine(int id)
        {
            UsersContext.SetOffLine(id);

        }

        public bool CheckExist(string name)
        {
            return _service.Exsist(name);
        }
    }
}

DChat/DChat.Web/Controllers/TalkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DChat.Web.Controllers
{
    public class TalkController : Controller
    {
        //
        // GET: /Talk/
        public ActionResult Index()
        {
            return View();
        }
	}
}

DChat/DChat.Web/Controllers/TestController.cs
using DChat.Framework.Cache;
using DChat.Framework.Log;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DChat.Web.Controllers
{
    public class TestController : Controller
    {
        private readonly ILogger _log;
        private readonly IRedisCache _cache;
        
        public TestController(ILogger log,IRedisCache cache)
        {
            _log = log;
            _cache = cache;
        }
        // GET: Test
        public ActionResult Index()
        {

            _log.Error("ERROR:test by fierce");
            _log.Debug("Debug:test by fierce");
            _log.Information("Information:test by fierce");
            _log.Fatal("Fatal:test by fierce");
            //RedisCache cache = new RedisCache();
            //_cache.Add("test1",new string[] { "111","222"});
            ViewBag.Test1 = _cache.Get<string[]>("test1");

            return View();
        }
    }
}

DChat/DChat.Web/Controllers/ViewSwitcherController.cs
using System.Web.Mvc;
using System.Web.WebPages;

namespace DChat.Web.Controllers
{
    public class ViewSwitcherController : Controller
    {
        public RedirectResult SwitchView(bool mobile, string returnUrl) {
            if (Request.Browser.IsMobileDevice == mobile)
                HttpContext.ClearOverriddenBrowser();
            else
                HttpContext.SetOverriddenBrowser(mobile ? BrowserOverride.Mobile : BrowserOverride.Desktop);

            return Redirect(returnUrl);
        }
    }
}

DChat/DChat.Web/Views/Member/Regester.cshtml
@{
    Layout = null;
}
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<link href="~/Scripts/webuploader-0.1.5/webuploader.css" rel="stylesheet" />
<!DOCTYPE html>
<html>
<head>
    <style>
        #uploader { margin-bottom: 10px; margin-top: 30px; }
        .form-group > input:not([type='submit']):not([type='radio']) { width: 300px; height: 30px; }
        .form-group label { font-family: 'SimSun'; font-weight: 300; }
        .form-title { font-size: 16px; font-weight: 600; padding-left: 15%; }
        .form-container { padding-top: 50px; }
        .webuploader-container { display: inline-block; vertical-align: bottom; }
        .pre-view { width: 100px; height: 100px; }
        .webuploader-pick { background: none; position: relative; display: inline-block; cursor: pointer; /* background: #00b7ee; */ padding: 5px 5px; color: #9B2E3F; text-align: center; border-radius: 3px; overflow: hidden; font-size: 6px; }
    </style>
    <meta name="viewport" content="width=device-width" />
    <title>Regester</title>
</head>
<body>
    <div class="container">
        <div class="col-md-8 col-md-offset-4">
            <div class="form-container">
                <div class="form-title">
                    填写个人信息
                </div>
                <form role="form" method="POST">
                    <div id="uploader">
                        <!--用来存放item-->
                        <input type="hidden" placeholder="头像" name="HeadImgPath" id="HeadImgPath" />
                        <img id="imgview" title="请上传头像" class="pre-view"></img>
                        <div id="filePicker">上传头像</div>
                    </div>
                    <div class="form-group">
                        <input type="text" placeholder="用户名" name="Name" id="Name" required="required" />
                    </div>
                    <div class="form-group">
                        <input type="text" placeholder="昵称" name="NickName" id="NickName" required="required" />
                    </div>
                    <div class="form-group">
                        <input type="email" placeholder="邮箱" name="Email" id="Email" required="required" />
                    </div>
                    <div class="form-group">
                        <input type="password" name="Password" id="Password" placeholder="输入密码" required="required" />
                    </div>
                    <div class="form-group">
                        <input type="text" name="ConfirPwd" id="ConfigPwd" placeholder="确认密码" required="required" />
                    </div>
                    <div class="form-group">
                        <label>选择性别:</label>
                        <label>男</label> <input type="radio" value="0" name="Six" />
                        <label>女</label> <input type="radio" value="1" name="Six" />
                    </div>
                    <div style="padding-left: 15%">
                        <input type="submit" value="提交" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
</html>
<script src="~/Scripts/jquery-2.1.4.min.js"></script>
<script src="~/Scripts/bootstrap.js"></script>
<script src="~/Scripts/webuploader-0.1.5/webuploader.js"></script>
<script>
    var UPLOAD_PATH = '';
</script>
<script>
    $("#ConfigPwd").focusout(function() {
        if ($("#Password").val() != $("#ConfigPwd").val())
            $("#ConfigPwd").get(0).setCustomValidity("两次输入的密码不一致.");
        else {
            $("#ConfigPwd").get(0).setCustomValidity("");
        }
    });
    $("#Name").focusout(function() {
        if (!($(this).val())) return;
        $.ajax({
            url: "CheckExist?name=" + $(this).val(),
            type: 'get',
            success: function(yes) {
                if (yes != "False") {
                    $("#Name").get(0).setCustomValidity("此用户名已被占用.");
                }
            }
        });

    });
</script>
<script>
    var uploader = WebUploader.create({
        auto: true,
        swf: '~/Scripts/webuploader-0.1.5/Uploader.swf',
        server: UPLOAD_PATH,
        pick: '#filePicker',
        multiple: true,
        accept: {
            title: 'Images',
            extensions: 'gif,jpg,jpeg,bmp,png',
            mimeTypes: 'image/*'
        },
        thumb: {
            width: 110,
            height: 110,

            // 图片质量，只有type为`image/jpeg`的时候才有效。
            quality: 70,

            // 是否允许放大，如果想要生成小图的时候不失真，此选项应该设置为false.
            allowMagnify: true,

            // 是否允许裁剪。
            crop: true,

            // 为空的话则保留原有图片格式。
            // 否则强制转换成指定的类型。
            type: 'image/jpeg'
        }

    });

    uploader.on('fileQueued', function (file) {
        //var $li = $(
        //        '<div id="' + file.id + '" class="file-item thumbnail">' +
        //            '<img>' +
        //            '<div class="info">' + file.name + '</div>' +
        //        '</div>'
        //        ),
        //    $img = $li.find('img');


        //// $list为容器jQuery实例
        //$("#fileList").append($li);

        // 创建缩略图
        // 如果为非图片文件，可以不用调用此方法。
        // thumbnailWidth x thumbnailHeight 为 100 x 100
        uploader.makeThumb(file, function (error, src) {
            if (error) {
                $("#imgview").attr("title", "不能预览");
                return;
            }
            $("#imgview").attr('src', src);
        }, 100, 100);
        // 文件上传过程中创建进度条实时显示。
        uploader.on('uploadProgress', function (file, percentage) {
            var $li = $('#' + file.id),
                $percent = $li.find('.progress span');

            // 避免重复创建
            if (!$percent.length) {
                $percent = $('<p class="progress"><span></span></p>')
                        .appendTo($li)
                        .find('span');
            }

            $percent.css('width', percentage * 100 + '%');
        });

        // 文件上传成功，给item添加成功class, 用样式标记上传成功。
        uploader.on('uploadSuccess', function (file) {
            $("#HeadImgPath").val();
            $('#').addClass('upload-state-done');
        });

        // 文件上传失败，显示上传出错。
        uploader.on('uploadError', function (file, respone) {
            var $li = $('#' + file.id),
                $error = $li.find('div.error');

            // 避免重复创建
            if (!$error.length) {
                $error = $('<div class="error"></div>').appendTo($li);
            }

            $error.text('上传失败');
        });

        // 完成上传完了，成功或者失败，先删除进度条。
        uploader.on('uploadComplete', function (file) {
            $('#' + file.id).find('.progress').remove();
        });
    });
</script>

DChat/DChat.Web/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html> 
<html> 
    <head> 
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title> 
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/Mobile/css", "~/Content/jquerymobile/css")
        @Scripts.Render("~/bundles/jquery", "~/bundles/jquerymobile")
        <script>
            $(document).ready(function () {
                $.mobile.ajaxEnabled = false; 
            });
        </script>
    </head> 
<body> 

    <div data-role="page" data-theme="a">
        @Html.Partial("_ViewSwitcher")

        <div data-role="header">
            <h1>@ViewBag.Title</h1>
        </div>

        <div data-role="content">
            @RenderSection("featured", false)
            @RenderBody()		
        </div>

    </div>

</body>
</html>

DChat/DChat.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

DChat/DChat.Web/Views/Shared/_ViewSwitcher.cshtml
@if (Request.Browser.IsMobileDevice && Request.HttpMethod == "GET")
{
    <div class="view-switcher ui-bar-a">
        @if (ViewContext.HttpContext.GetOverriddenBrowser().IsMobileDevice)
        {
            @: Displaying mobile view
            @Html.ActionLink("Desktop view", "SwitchView", "ViewSwitcher", new { mobile = false, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        } 
        else 
        {
            @: Displaying desktop view
            @Html.ActionLink("Mobile view", "SwitchView", "ViewSwitcher", new { mobile = true, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        }
    </div>
}

DChat/DChat.Web/Views/Talk/Index - 复制.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <style>
        .login {height: 100%;width: 100%;position: fixed;top: 0;left: 0;background-color: rgba(0, 0, 0, 0.3);text-align: center;padding-top: 15%; }
        .login form { padding: 10px; }
            .login input[type='text'] { height: 30px; border: none; width: 215px; }
        .login > div {background-color: white;width: 380px;display: inline-block; }
        .tang-title {background-color: #f7f7f7;padding: 10px;text-align: left;padding-left: 10%;color: #666;font-family: sans-serif; }
        .reg-con {font-size: 10px;text-align: right;padding-right: 20px; }
        .reg-con a { color: #2e7fdb; }
        .login div.input-con { width: 250px; border: 1px solid #ccc; /* margin: 5px; */ margin: 5px 15%; }
        
    </style>
    <link href="~/Content/icono.min.css" rel="stylesheet" /> 
    <link href="~/Content/css/index.css" rel="stylesheet" />
    @*<link href="~/content/icono.min.css" rel="stylesheet" />*@
    <meta name="viewport" content="width=device-width" />
    <title>Daker</title>
</head>
<body>
    <!--聊天框-->
    <div id="container" class="enviroment-big">
        <div class="msg-list">
            <div class="left">
                <div class="head">
                    <img src="~/images/1.jpg" /><div class="nickname">AAA</div>
                </div>
                <div class="mscontent">
                    asdasda
                </div>
            </div>
            <div class="right">
                <div class="mscontent">
                    addads
                </div>
                <div class="head">
                    <img src="~/images/1.jpg" />
                </div>
            </div>
        </div>
        <div class="typearea">
            <div style="border:none;"><input type="text" class="msg" placeholder="输入..." /><a class="sendbtn"><span class=" icon"><span class="text">发送</span></span>  </a> </div><div></div>
        </div>
    </div>
    <!--聊天框 end-->
    <!--登录-->
    <div class="login">

        <div>
            <div class="tang-title">
                登录到DAKER
            </div>
            <form id="fm">

                <div>
                    <div class="input-con">
                        <span class="icono-user"></span><input type="text" name="Name" id="Name" />
                    </div>
                </div>
                <div>
                    <div class="input-con">
                        <span class="icono-flickr"></span><input type="text" name="Password" id="Password" />
                    </div>
                   
                </div>
                <div>
                    <a id="login" href="#" style="cursor: pointer">登录</a>
                </div>
                <div class="reg-con">
                    <a id="reg" href="@Url.Action("Regester","Member")">立即注册</a>
                </div>
            </form>

        </div>
    </div>
</body>
</html>
<script src="~/Scripts/jquery-2.1.4.min.js"></script>
<script>


    var dChat = {
        config: {
            maxMsgLength: 100,
            maxExistDom: 10,
            requestTimeout: 5,
            waitTimeout: 3,
        },
        Index: 0,
        tempIndex: 0,
        user: {
            NickName: "ZS"
        }
        ,
        initial: function (dom, user, msgs) {
            if (!dom) {
                throw new DOMException("dom not exist");
            }
            var usr = dChat.getUser(user);
            dChat.user = usr;
            this.get();

        }
        ,

        get: function () {
            $.ajax(
               {
                   url: 'http://localhost:53432/Message/get?id=' + dChat.Index,
                   type: 'get',
                   datatype: 'jsonp',
                   jsonp: 'callback',
                   //  timeout: dChat.config.waitTimeout,
                   success: function (data) {

                       //data = [
                       //    { MsgContent: "aaa", Id: "asadsadsdasdsaad", SendTime: new Date(), Sender: { Id: 1, Name: "张三", NickName: "Zhang-San", HeadImgPath: "../images/1.jpg" } },
                       //    { MsgContent: "bbb", Id: "bbbb", SendTime: new Date(), Sender: { Id: 1, Name: "张si", NickName: "Zhang-Si", HeadImgPath: "../images/2.jpg" } }
                       //];
                       //alert(data[data.length-1].Id);
                       //var jsondata = data;
                       //Get的消息记录条数大于0
                       if (data.length > 0) {
                           dChat.Index = data[data.length - 1].Id;
                           dChat.popMsgs(data, false);
                       }
                       dChat.get();

                   },
                   error: function () {

                   },
                   complete: function () {

                   }
               }
                )
        },
        TestGet: function () {
            var x = Math.random();
            var waittime = x < 0.5 ? 2 : x * 5;
            dChat.send(waittime.toString(), false);
            setTimeout(dChat.TestGet, waittime * 1000);
        }
        ,
        send: function (msg, left) {
            var msgObject = { MsgContent: msg, Sender: { HeadImgPath: '../images/1.jpg', NickName: 'Json' } }
            $.ajax({
                url: 'http://localhost:53432/Message/push?value=' + msg,
                data: JSON.stringify({ MsgContent: msg, UserId: 1, Sender: { UserId: 1, NickName: 'Daker', Name: 'Daker' } }),
                type: "post",
                contenttype: "application/json",
                datatype: 'jsonp',
                jsonp: 'callback'
            });
            dChat.popMsgs(msgObject, true);


        },
        popMsgs: function (msg, left) {
            if (msg instanceof Array) {
                for (var i = 0; i < msg.length; i++) {
                    if (dChat.checkMsg(msg[i])) {
                        dChat.popMsg(msg[i], left);
                    }
                }
            }
            else if (dChat.checkMsg(msg)) {
                dChat.popMsg(msg, left);
            }
        }
        ,
        popMsg: function (data, isright) {
            var msg = decodeURI(data.MsgContent);
            var sender = data.Sender;
            if (isright) {
                var msbody = $("<div>").addClass("right").append($("<div>").addClass("mscontent").text(msg)).append($("<div>").addClass("head").append($("<img>").attr("src", sender.HeadImgPath)));
                $(".msg-list").append(msbody);
            } else {
                var msbody = $("<div>").addClass("left").append($("<div>").addClass("head").append($("<img>").attr("src", sender.HeadImgPath)).append($("<div>").addClass("nickname").text(sender.NickName))).append($("<div>").addClass("mscontent").text(msg));
                $(".msg-list").append(msbody);
            }
            if ($(".msg-list>.left,.msg-list>.right").length > dChat.config.maxExistDom) {
                var rmIndex = $(".msg-list>.left,.msg-list>.right").length - dChat.config.maxExistDom;
                var extraDoms = $(".msg-list>div:lt(" + rmIndex + ")");
                extraDoms.remove();
            }
            var height = $(".msg-list").get(0).scrollHeight;
            //HandleScroll();
            $(".msg-list").animate({ scrollTop: height }, 800);

        }
        ,
        checkMsg: function (msg) {
            if (!msg || msg.length > dChat.config.maxMsgLength) {
                return false;
            }
            return true;

        },
        getUser: function (user) {
            if (!user || !("Name" in user)) {
                return {
                    Name: "匿名用户",
                    ID: ""
                }
            }

        },
        PauseScroll: function () {

        },
        ScrollSate: { WaiteTime: 2, InPause: true, handled: false },
        HandleScroll: function () {
            if (this.ScrollSate.InPause && !this.ScrollSate.handled) {
                this.ScrollSate.handled = true;
                setTimeout($.proxy(function () {
                    this.InPause = false;
                }, this), this.ScrollSate.WaiteTime);
            }

        }


    };
    //发送
    function sendMsg() {

        var msg = $(".typearea .msg").val();
        $(".typearea .msg").val("");
        dChat.send(msg, true);
    };
    //点击发送
    $(".sendbtn").click(function () {
        sendMsg();
    });
    //ctrl+enter发送
    $(document).keydown(function (event) {
        if (event.ctrlKey && event.keyCode == 13) {
            sendMsg();
        }
    });
    function CircleGet() {
        dChat.get();


    }

    $("#login").click(function () {
        var name = $("#Name").val();
        var pwd = $("#Password").val();
        if (!name || !pwd) {
            alert("请输入用户名密码.");
            return;
        }
        $.ajax({
            url: "../Member/Login",
            type: 'post',
            data: $("#fm").serialize(),
            datatype: 'json',
            success: function (jsondata) {
                if (jsondata.status) {

                    dChat.initial($(".msg-list"), jsondata.Data);
                } else {
                    {
                        alert("用户名或密码错误.");

                    }
                }


            }, error: function () {
                alert("服务器错误.");
            }

        });

    });





</script>
<script>
</script>

DChat/DChat.Web/Views/Test/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@foreach (string s in (string[])ViewBag.Test1)
{
    <h3>@s</h3>
}

DChat/DChat.Web/Views/home/Index.cshtml
@model DChat.Model.Models.UserInfo
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        <h6>你好,@Model.Name</h6>
    </div>
    <div>
        <a href="@Url.Action("Index", "Talk")">去聊天</a>
        <a href="@Url.Action("Index", "Talk")">去论坛</a>
        <a href="@Url.Action("Index", "Talk")">随便看看</a>
    </div>
</body>
</html>